import pg from 'pg';
const { Client } = pg;
const client = new Client({ connectionString: process.env.SUPABASE_DB_URL, ssl: { rejectUnauthorized: false } });
await client.connect();
const t = await client.query(`select table_name from information_schema.tables where table_schema='public' order by table_name`);
console.log('TABLES:', t.rows.map(r=>r.table_name).join(', '));
const b = await client.query(`select id, public from storage.buckets order by id`);
console.log('BUCKETS:', JSON.stringify(b.rows));
const f = await client.query(`select routine_name from information_schema.routines where routine_schema='public' order by routine_name`);
console.log('FUNCTIONS:', f.rows.map(r=>r.routine_name).join(', '));
const p = await client.query(`select tablename, count(*) from pg_policies where schemaname='public' group by tablename order by tablename`);
console.log('POLICIES:', JSON.stringify(p.rows));
await client.end();
